### ISSUE TITLE
APPs Removed From Google PLAY due ADFRAUD.

### ISSUE THREAD

**Issue by samutec1** [kmcgill88/admob_flutter#278]
Two Apps that I was using admob_flutter were removed from Google play, I've update with ADmob Oficial library, I let you guys know if it was due this API or I made something wrong, tks.

**Comment by RaulMarquezInclan** [comment]
This has happened to me as well, already provided two updates that were declined.

My app was already doing fine for about 8 months. As we speak my latest update is in review, I removed the plugin and ads as a last resort, not very important at this stage since I haven't yet been able to reach the $$ monthly threshhold to have a deposit. I'm still relying on IAP for revenue.

I would also like to know if it's somehow related to some mismatch between updates to Google's ad policies and this plugins code.

This is the reason they gave me:

_During review, we found that your app is not compliant with the Ad Fraud policy. Ad fraud is strictly prohibited. Ad interactions generated for the purpose of tricking an ad network into believing traffic is from authentic user interest is ad fraud, which is a form of invalid traffic. Ads should not be shown in a way that results in inadvertent clicks. Forcing a user to click an ad or submit personal information for advertising purposes before they can fully use an app is prohibited. **Ads should not appear after the user has exited the app, or after the user has pressed the back button to exit the app.**_

On that last part, my app has never done that.

**Comment by samutec1** [comment]
> This has happened to me as well, already provided two updates that were declined.
> 
> My app was already doing fine for about 8 months. As we speak my latest update is in review, I removed the plugin and ads as a last resort, not very important at this stage since I haven't yet been able to reach the $$ monthly threshhold to have a deposit. I'm still relying on IAP for revenue.
> 
> I would also like to know if it's somehow related to some mismatch between updates to Google's ad policies and this plugins code.
> 
> This is the reason they gave me:
> 
> _During review, we found that your app is not compliant with the Ad Fraud policy. Ad fraud is strictly prohibited. Ad interactions generated for the purpose of tricking an ad network into believing traffic is from authentic user interest is ad fraud, which is a form of invalid traffic. Ads should not be shown in a way that results in inadvertent clicks. Forcing a user to click an ad or submit personal information for advertising purposes before they can fully use an app is prohibited. **Ads should not appear after the user has exited the app, or after the user has pressed the back button to exit the app.**_
> 
> On that last part, my app has never done that.
> 
> using
> admob_flutter: ^1.0.1
> 
> @samutec1, can you provide the reason they gave you as well? Maybe we can start figuring this out together.

I let you know if I get success on my new update.

**Comment by RaulMarquezInclan** [comment]
Just as an update, my app just went live again.

To clarify, my first update only removed the display of ads, but I left the plugin in pubsec.yaml, on this second live update, I removed it.

So it sure sounds it's an issue with the plugin code.

**Comment by armandojimenez** [comment]
I'm about to upload my app, is this still an issue? I'm only using rewarded ads with this plugin

**Comment by lpancho** [comment]
What kind of ads are you using in your app? I'm just using banner ads and it is just fine.

**Comment by rodrigolmacedo** [comment]
strange... check if you show ads without remove previous instance...

**Comment by syedecryptr** [comment]
What official library are you referencing to? Can you share some links/references/guide for that?
